#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BystronicSalesService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BystronicSales")]
	public partial class BystronicDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public BystronicDataDataContext() : 
				base(global::BystronicSalesService.Properties.Settings.Default.BystronicSalesConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BystronicDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BystronicDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BystronicDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BystronicDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CustomerList> CustomerLists
		{
			get
			{
				return this.GetTable<CustomerList>();
			}
		}
		
		public System.Data.Linq.Table<RegionList> RegionLists
		{
			get
			{
				return this.GetTable<RegionList>();
			}
		}
		
		public System.Data.Linq.Table<OrderList> OrderLists
		{
			get
			{
				return this.GetTable<OrderList>();
			}
		}
		
		public System.Data.Linq.Table<PaymentList> PaymentLists
		{
			get
			{
				return this.GetTable<PaymentList>();
			}
		}
		
		public System.Data.Linq.Table<ProductCategoryList> ProductCategoryLists
		{
			get
			{
				return this.GetTable<ProductCategoryList>();
			}
		}
		
		public System.Data.Linq.Table<ProductList> ProductLists
		{
			get
			{
				return this.GetTable<ProductList>();
			}
		}
		
		public System.Data.Linq.Table<RegionalManagerList> RegionalManagerLists
		{
			get
			{
				return this.GetTable<RegionalManagerList>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AddCustomer")]
		public int AddCustomer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SAPNumber", DbType="VarChar(50)")] string sAPNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(MAX)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="City", DbType="VarChar(MAX)")] string city, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="State", DbType="VarChar(50)")] string state, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReginalManagerID", DbType="Int")] System.Nullable<int> reginalManagerID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateJoined", DbType="Date")] System.Nullable<System.DateTime> dateJoined, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="NChar(10)")] string status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sAPNumber, name, city, state, reginalManagerID, dateJoined, status);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateRegionalManager")]
		public int UpdateRegionalManager([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegionalManagerName", DbType="VarChar(MAX)")] string regionalManagerName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegionID", DbType="Int")] System.Nullable<int> regionID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, regionalManagerName, regionID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AddOrder")]
		public int AddOrder(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EquipmentNumber", DbType="VarChar(50)")] string equipmentNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerID", DbType="Int")] System.Nullable<int> customerID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductID", DbType="Int")] System.Nullable<int> productID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SaleAmount", DbType="Decimal(18,0)")] System.Nullable<decimal> saleAmount, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SAPNumber", DbType="VarChar(MAX)")] string sAPNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PONumber", DbType="VarChar(MAX)")] string pONumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="KNumber", DbType="VarChar(50)")] string kNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PortDate", DbType="Date")] System.Nullable<System.DateTime> portDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Port", DbType="VarChar(50)")] string port, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ForwarderNumber", DbType="VarChar(50)")] string forwarderNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DeliveryDate", DbType="Date")] System.Nullable<System.DateTime> deliveryDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MfgDate", DbType="Date")] System.Nullable<System.DateTime> mfgDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="InstallDate", DbType="Date")] System.Nullable<System.DateTime> installDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Shipped", DbType="NChar(10)")] string shipped, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShipDate", DbType="Date")] System.Nullable<System.DateTime> shipDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductionWeek", DbType="VarChar(MAX)")] string productionWeek, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SaleOrderNumber", DbType="VarChar(50)")] string saleOrderNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Comments", DbType="VarChar(MAX)")] string comments, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Options", DbType="VarChar(MAX)")] string options, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="VarChar(50)")] string status, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FirstInstallDate", DbType="Date")] System.Nullable<System.DateTime> firstInstallDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FirstInstallAmount", DbType="Decimal(18,4)")] System.Nullable<decimal> firstInstallAmount, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SecondInstallDate", DbType="Date")] System.Nullable<System.DateTime> secondInstallDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SecondInstallAmount", DbType="Decimal(18,4)")] System.Nullable<decimal> secondInstallAmount, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FinalInstallDate", DbType="Date")] System.Nullable<System.DateTime> finalInstallDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FinalInstallAmount", DbType="Decimal(18,4)")] System.Nullable<decimal> finalInstallAmount, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="InstallmentTerm", DbType="VarChar(MAX)")] string installmentTerm, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="InstallmentNote", DbType="VarChar(MAX)")] string installmentNote)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), equipmentNumber, customerID, productID, saleAmount, sAPNumber, pONumber, kNumber, portDate, port, forwarderNumber, deliveryDate, mfgDate, installDate, shipped, shipDate, productionWeek, saleOrderNumber, comments, options, status, firstInstallDate, firstInstallAmount, secondInstallDate, secondInstallAmount, finalInstallDate, finalInstallAmount, installmentTerm, installmentNote);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AddPayment")]
		public int AddPayment([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderID", DbType="Int")] System.Nullable<int> orderID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FirstInstallDate", DbType="Date")] System.Nullable<System.DateTime> firstInstallDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FirstInstallAmount", DbType="Decimal(18,4)")] System.Nullable<decimal> firstInstallAmount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SecondInstallDate", DbType="Date")] System.Nullable<System.DateTime> secondInstallDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SecondInstallAmount", DbType="Decimal(18,4)")] System.Nullable<decimal> secondInstallAmount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FinalInstallDate", DbType="Date")] System.Nullable<System.DateTime> finalInstallDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FinalInstallAmount", DbType="Decimal(18,4)")] System.Nullable<decimal> finalInstallAmount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Term", DbType="VarChar(50)")] string term, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Note", DbType="VarChar(MAX)")] string note)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), orderID, firstInstallDate, firstInstallAmount, secondInstallDate, secondInstallAmount, finalInstallDate, finalInstallAmount, term, note);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AddProduct")]
		public int AddProduct([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductName", DbType="VarChar(MAX)")] string productName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryID", DbType="Int")] System.Nullable<int> categoryID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="NChar(10)")] string status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), productName, categoryID, status);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AddProductCategory")]
		public int AddProductCategory([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryTypeId", DbType="Int")] System.Nullable<int> categoryTypeId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Category", DbType="VarChar(MAX)")] string category, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="NChar(10)")] string status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), categoryTypeId, category, status);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AddRegion")]
		public int AddRegion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegionName", DbType="VarChar(MAX)")] string regionName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), regionName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AddRegionalManager")]
		public int AddRegionalManager([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegionalManagerName", DbType="VarChar(MAX)")] string regionalManagerName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegionID", DbType="Int")] System.Nullable<int> regionID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), regionalManagerName, regionID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AddUpdateUsersGridColumns")]
		public int AddUpdateUsersGridColumns([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="VarChar(50)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GridName", DbType="VarChar(50)")] string gridName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NewGridName", DbType="VarChar(50)")] string newGridName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Columns", DbType="VarChar(1500)")] string columns)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName, gridName, newGridName, columns);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteAllGridsByUser")]
		public int DeleteAllGridsByUser([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="VarChar(50)")] string userName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteCustomer")]
		public ISingleResult<DeleteCustomerResult> DeleteCustomer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerID", DbType="Int")] System.Nullable<int> customerID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), customerID);
			return ((ISingleResult<DeleteCustomerResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteGridByUserAndGridName")]
		public int DeleteGridByUserAndGridName([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="VarChar(50)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GridName", DbType="VarChar(50)")] string gridName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName, gridName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteOrder")]
		public int DeleteOrder([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderID", DbType="Int")] System.Nullable<int> orderID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), orderID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteProduct")]
		public ISingleResult<DeleteProductResult> DeleteProduct([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductID", DbType="Int")] System.Nullable<int> productID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), productID);
			return ((ISingleResult<DeleteProductResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetGridcolumnsByUser")]
		public ISingleResult<GetGridcolumnsByUserResult> GetGridcolumnsByUser([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="VarChar(50)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GridName", DbType="VarChar(50)")] string gridName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName, gridName);
			return ((ISingleResult<GetGridcolumnsByUserResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetViewsByUser")]
		public ISingleResult<GetViewsByUserResult> GetViewsByUser([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="VarChar(50)")] string userName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName);
			return ((ISingleResult<GetViewsByUserResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateCustomer")]
		public int UpdateCustomer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SAPNumber", DbType="VarChar(50)")] string sAPNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(MAX)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="City", DbType="VarChar(MAX)")] string city, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="State", DbType="VarChar(50)")] string state, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReginalManagerID", DbType="Int")] System.Nullable<int> reginalManagerID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateJoined", DbType="Date")] System.Nullable<System.DateTime> dateJoined, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="NChar(10)")] string status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, sAPNumber, name, city, state, reginalManagerID, dateJoined, status);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateOrder")]
		public int UpdateOrder(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EquipmentNumber", DbType="VarChar(50)")] string equipmentNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerID", DbType="Int")] System.Nullable<int> customerID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductID", DbType="Int")] System.Nullable<int> productID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SaleAmount", DbType="Decimal(18,0)")] System.Nullable<decimal> saleAmount, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SAPNumber", DbType="VarChar(MAX)")] string sAPNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PONumber", DbType="VarChar(MAX)")] string pONumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="KNumber", DbType="VarChar(50)")] string kNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PortDate", DbType="Date")] System.Nullable<System.DateTime> portDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Port", DbType="VarChar(50)")] string port, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ForwarderNumber", DbType="VarChar(50)")] string forwarderNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DeliveryDate", DbType="Date")] System.Nullable<System.DateTime> deliveryDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MfgDate", DbType="Date")] System.Nullable<System.DateTime> mfgDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="InstallDate", DbType="Date")] System.Nullable<System.DateTime> installDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Shipped", DbType="NChar(10)")] string shipped, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShipDate", DbType="Date")] System.Nullable<System.DateTime> shipDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductionWeek", DbType="VarChar(MAX)")] string productionWeek, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SaleOrderNumber", DbType="VarChar(50)")] string saleOrderNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Comments", DbType="VarChar(MAX)")] string comments, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Options", DbType="VarChar(MAX)")] string options, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="VarChar(50)")] string status, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FirstInstallDate", DbType="Date")] System.Nullable<System.DateTime> firstInstallDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FirstInstallAmount", DbType="Decimal(18,4)")] System.Nullable<decimal> firstInstallAmount, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SecondInstallDate", DbType="Date")] System.Nullable<System.DateTime> secondInstallDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SecondInstallAmount", DbType="Decimal(18,4)")] System.Nullable<decimal> secondInstallAmount, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FinalInstallDate", DbType="Date")] System.Nullable<System.DateTime> finalInstallDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FinalInstallAmount", DbType="Decimal(18,4)")] System.Nullable<decimal> finalInstallAmount, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="InstallmentTerm", DbType="VarChar(MAX)")] string installmentTerm, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="InstallmentNote", DbType="VarChar(MAX)")] string installmentNote)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, equipmentNumber, customerID, productID, saleAmount, sAPNumber, pONumber, kNumber, portDate, port, forwarderNumber, deliveryDate, mfgDate, installDate, shipped, shipDate, productionWeek, saleOrderNumber, comments, options, status, firstInstallDate, firstInstallAmount, secondInstallDate, secondInstallAmount, finalInstallDate, finalInstallAmount, installmentTerm, installmentNote);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdatePayment")]
		public int UpdatePayment([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderID", DbType="Int")] System.Nullable<int> orderID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FirstInstallDate", DbType="Date")] System.Nullable<System.DateTime> firstInstallDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FirstInstallAmount", DbType="Decimal(18,4)")] System.Nullable<decimal> firstInstallAmount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SecondInstallDate", DbType="Date")] System.Nullable<System.DateTime> secondInstallDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SecondInstallAmount", DbType="Decimal(18,4)")] System.Nullable<decimal> secondInstallAmount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FinalInstallDate", DbType="Date")] System.Nullable<System.DateTime> finalInstallDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FinalInstallAmount", DbType="Decimal(18,4)")] System.Nullable<decimal> finalInstallAmount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Term", DbType="VarChar(50)")] string term, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Note", DbType="VarChar(MAX)")] string note)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, orderID, firstInstallDate, firstInstallAmount, secondInstallDate, secondInstallAmount, finalInstallDate, finalInstallAmount, term, note);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateProduct")]
		public int UpdateProduct([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductName", DbType="VarChar(MAX)")] string productName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryID", DbType="Int")] System.Nullable<int> categoryID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="NChar(10)")] string status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, productName, categoryID, status);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateProductCategory")]
		public int UpdateProductCategory([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryTypeId", DbType="Int")] System.Nullable<int> categoryTypeId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Category", DbType="VarChar(MAX)")] string category, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="NChar(10)")] string status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, categoryTypeId, category, status);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateRegion")]
		public int UpdateRegion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegionName", DbType="VarChar(MAX)")] string regionName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, regionName);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CustomerList")]
	public partial class CustomerList
	{
		
		private int _Id;
		
		private string _SAPNumber;
		
		private string _Name;
		
		private string _City;
		
		private string _State;
		
		private System.Nullable<int> _ReginalManagerID;
		
		private System.Nullable<System.DateTime> _DateJoined;
		
		private string _Status;
		
		public CustomerList()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAPNumber", DbType="VarChar(50)")]
		public string SAPNumber
		{
			get
			{
				return this._SAPNumber;
			}
			set
			{
				if ((this._SAPNumber != value))
				{
					this._SAPNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(MAX)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(MAX)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(50)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this._State = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReginalManagerID", DbType="Int")]
		public System.Nullable<int> ReginalManagerID
		{
			get
			{
				return this._ReginalManagerID;
			}
			set
			{
				if ((this._ReginalManagerID != value))
				{
					this._ReginalManagerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateJoined", DbType="Date")]
		public System.Nullable<System.DateTime> DateJoined
		{
			get
			{
				return this._DateJoined;
			}
			set
			{
				if ((this._DateJoined != value))
				{
					this._DateJoined = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RegionList")]
	public partial class RegionList
	{
		
		private int _Id;
		
		private string _RegionName;
		
		public RegionList()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegionName", DbType="VarChar(50)")]
		public string RegionName
		{
			get
			{
				return this._RegionName;
			}
			set
			{
				if ((this._RegionName != value))
				{
					this._RegionName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OrderList")]
	public partial class OrderList
	{
		
		private int _Id;
		
		private string _EquipmentNumber;
		
		private System.Nullable<System.DateTime> _DateAdded;
		
		private int _CustomerID;
		
		private int _ProductID;
		
		private System.Nullable<decimal> _SaleAmount;
		
		private string _PONumber;
		
		private System.Nullable<System.DateTime> _PortDate;
		
		private System.Nullable<System.DateTime> _DeliveryDate;
		
		private System.Nullable<System.DateTime> _InstallDate;
		
		private string _Shipped;
		
		private System.Nullable<System.DateTime> _ShipDate;
		
		private string _ProductionWeek;
		
		private string _SaleOrderNumber;
		
		private System.Nullable<System.DateTime> _MfgDate;
		
		private string _ForwarderNumber;
		
		private string _Port;
		
		private string _KNumber;
		
		private string _Options;
		
		private string _Comments;
		
		private string _SAPNumber;
		
		private string _Status;
		
		private System.Nullable<System.DateTime> _FirstInstallDate;
		
		private System.Nullable<decimal> _FirstInstallAmount;
		
		private System.Nullable<System.DateTime> _SecondInstallDate;
		
		private System.Nullable<decimal> _SecondInstallAmount;
		
		private System.Nullable<System.DateTime> _FinalInstallDate;
		
		private System.Nullable<decimal> _FinalInstallAmount;
		
		private string _InstallmentTerm;
		
		private string _InstallmentNote;
		
		public OrderList()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EquipmentNumber", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EquipmentNumber
		{
			get
			{
				return this._EquipmentNumber;
			}
			set
			{
				if ((this._EquipmentNumber != value))
				{
					this._EquipmentNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateAdded", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateAdded
		{
			get
			{
				return this._DateAdded;
			}
			set
			{
				if ((this._DateAdded != value))
				{
					this._DateAdded = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerID", DbType="Int NOT NULL")]
		public int CustomerID
		{
			get
			{
				return this._CustomerID;
			}
			set
			{
				if ((this._CustomerID != value))
				{
					this._CustomerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductID", DbType="Int NOT NULL")]
		public int ProductID
		{
			get
			{
				return this._ProductID;
			}
			set
			{
				if ((this._ProductID != value))
				{
					this._ProductID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaleAmount", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> SaleAmount
		{
			get
			{
				return this._SaleAmount;
			}
			set
			{
				if ((this._SaleAmount != value))
				{
					this._SaleAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PONumber", DbType="VarChar(MAX)")]
		public string PONumber
		{
			get
			{
				return this._PONumber;
			}
			set
			{
				if ((this._PONumber != value))
				{
					this._PONumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortDate", DbType="Date")]
		public System.Nullable<System.DateTime> PortDate
		{
			get
			{
				return this._PortDate;
			}
			set
			{
				if ((this._PortDate != value))
				{
					this._PortDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeliveryDate", DbType="Date")]
		public System.Nullable<System.DateTime> DeliveryDate
		{
			get
			{
				return this._DeliveryDate;
			}
			set
			{
				if ((this._DeliveryDate != value))
				{
					this._DeliveryDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstallDate", DbType="Date")]
		public System.Nullable<System.DateTime> InstallDate
		{
			get
			{
				return this._InstallDate;
			}
			set
			{
				if ((this._InstallDate != value))
				{
					this._InstallDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shipped", DbType="NChar(10)")]
		public string Shipped
		{
			get
			{
				return this._Shipped;
			}
			set
			{
				if ((this._Shipped != value))
				{
					this._Shipped = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipDate", DbType="Date")]
		public System.Nullable<System.DateTime> ShipDate
		{
			get
			{
				return this._ShipDate;
			}
			set
			{
				if ((this._ShipDate != value))
				{
					this._ShipDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductionWeek", DbType="VarChar(MAX)")]
		public string ProductionWeek
		{
			get
			{
				return this._ProductionWeek;
			}
			set
			{
				if ((this._ProductionWeek != value))
				{
					this._ProductionWeek = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaleOrderNumber", DbType="VarChar(50)")]
		public string SaleOrderNumber
		{
			get
			{
				return this._SaleOrderNumber;
			}
			set
			{
				if ((this._SaleOrderNumber != value))
				{
					this._SaleOrderNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MfgDate", DbType="Date")]
		public System.Nullable<System.DateTime> MfgDate
		{
			get
			{
				return this._MfgDate;
			}
			set
			{
				if ((this._MfgDate != value))
				{
					this._MfgDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ForwarderNumber", DbType="VarChar(50)")]
		public string ForwarderNumber
		{
			get
			{
				return this._ForwarderNumber;
			}
			set
			{
				if ((this._ForwarderNumber != value))
				{
					this._ForwarderNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Port", DbType="VarChar(50)")]
		public string Port
		{
			get
			{
				return this._Port;
			}
			set
			{
				if ((this._Port != value))
				{
					this._Port = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KNumber", DbType="VarChar(50)")]
		public string KNumber
		{
			get
			{
				return this._KNumber;
			}
			set
			{
				if ((this._KNumber != value))
				{
					this._KNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Options", DbType="VarChar(50)")]
		public string Options
		{
			get
			{
				return this._Options;
			}
			set
			{
				if ((this._Options != value))
				{
					this._Options = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comments", DbType="VarChar(MAX)")]
		public string Comments
		{
			get
			{
				return this._Comments;
			}
			set
			{
				if ((this._Comments != value))
				{
					this._Comments = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAPNumber", DbType="VarChar(MAX)")]
		public string SAPNumber
		{
			get
			{
				return this._SAPNumber;
			}
			set
			{
				if ((this._SAPNumber != value))
				{
					this._SAPNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstInstallDate", DbType="Date")]
		public System.Nullable<System.DateTime> FirstInstallDate
		{
			get
			{
				return this._FirstInstallDate;
			}
			set
			{
				if ((this._FirstInstallDate != value))
				{
					this._FirstInstallDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstInstallAmount", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> FirstInstallAmount
		{
			get
			{
				return this._FirstInstallAmount;
			}
			set
			{
				if ((this._FirstInstallAmount != value))
				{
					this._FirstInstallAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondInstallDate", DbType="Date")]
		public System.Nullable<System.DateTime> SecondInstallDate
		{
			get
			{
				return this._SecondInstallDate;
			}
			set
			{
				if ((this._SecondInstallDate != value))
				{
					this._SecondInstallDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondInstallAmount", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> SecondInstallAmount
		{
			get
			{
				return this._SecondInstallAmount;
			}
			set
			{
				if ((this._SecondInstallAmount != value))
				{
					this._SecondInstallAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinalInstallDate", DbType="Date")]
		public System.Nullable<System.DateTime> FinalInstallDate
		{
			get
			{
				return this._FinalInstallDate;
			}
			set
			{
				if ((this._FinalInstallDate != value))
				{
					this._FinalInstallDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinalInstallAmount", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> FinalInstallAmount
		{
			get
			{
				return this._FinalInstallAmount;
			}
			set
			{
				if ((this._FinalInstallAmount != value))
				{
					this._FinalInstallAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstallmentTerm", DbType="VarChar(MAX)")]
		public string InstallmentTerm
		{
			get
			{
				return this._InstallmentTerm;
			}
			set
			{
				if ((this._InstallmentTerm != value))
				{
					this._InstallmentTerm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstallmentNote", DbType="VarChar(50)")]
		public string InstallmentNote
		{
			get
			{
				return this._InstallmentNote;
			}
			set
			{
				if ((this._InstallmentNote != value))
				{
					this._InstallmentNote = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PaymentList")]
	public partial class PaymentList
	{
		
		private int _Id;
		
		private int _OrderID;
		
		private System.Nullable<System.DateTime> _FirstInstallDate;
		
		private System.Nullable<decimal> _FirstInstallAmount;
		
		private System.Nullable<System.DateTime> _SecondInstallDate;
		
		private System.Nullable<decimal> _SecondInstallAmount;
		
		private System.Nullable<System.DateTime> _FinalInstallDate;
		
		private System.Nullable<decimal> _FinalInstallAmount;
		
		private string _Term;
		
		private string _Note;
		
		public PaymentList()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderID", DbType="Int NOT NULL")]
		public int OrderID
		{
			get
			{
				return this._OrderID;
			}
			set
			{
				if ((this._OrderID != value))
				{
					this._OrderID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstInstallDate", DbType="Date")]
		public System.Nullable<System.DateTime> FirstInstallDate
		{
			get
			{
				return this._FirstInstallDate;
			}
			set
			{
				if ((this._FirstInstallDate != value))
				{
					this._FirstInstallDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstInstallAmount", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> FirstInstallAmount
		{
			get
			{
				return this._FirstInstallAmount;
			}
			set
			{
				if ((this._FirstInstallAmount != value))
				{
					this._FirstInstallAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondInstallDate", DbType="Date")]
		public System.Nullable<System.DateTime> SecondInstallDate
		{
			get
			{
				return this._SecondInstallDate;
			}
			set
			{
				if ((this._SecondInstallDate != value))
				{
					this._SecondInstallDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondInstallAmount", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> SecondInstallAmount
		{
			get
			{
				return this._SecondInstallAmount;
			}
			set
			{
				if ((this._SecondInstallAmount != value))
				{
					this._SecondInstallAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinalInstallDate", DbType="Date")]
		public System.Nullable<System.DateTime> FinalInstallDate
		{
			get
			{
				return this._FinalInstallDate;
			}
			set
			{
				if ((this._FinalInstallDate != value))
				{
					this._FinalInstallDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinalInstallAmount", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> FinalInstallAmount
		{
			get
			{
				return this._FinalInstallAmount;
			}
			set
			{
				if ((this._FinalInstallAmount != value))
				{
					this._FinalInstallAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Term", DbType="VarChar(50)")]
		public string Term
		{
			get
			{
				return this._Term;
			}
			set
			{
				if ((this._Term != value))
				{
					this._Term = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="VarChar(MAX)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this._Note = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProductCategoryList")]
	public partial class ProductCategoryList
	{
		
		private int _Id;
		
		private int _CategoryTypeId;
		
		private string _Category;
		
		private string _Status;
		
		public ProductCategoryList()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryTypeId", DbType="Int NOT NULL")]
		public int CategoryTypeId
		{
			get
			{
				return this._CategoryTypeId;
			}
			set
			{
				if ((this._CategoryTypeId != value))
				{
					this._CategoryTypeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="VarChar(50)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this._Category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProductList")]
	public partial class ProductList
	{
		
		private int _Id;
		
		private string _ProductName;
		
		private System.Nullable<int> _CategoryID;
		
		private string _Status;
		
		public ProductList()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="VarChar(50)")]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this._ProductName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryID", DbType="Int")]
		public System.Nullable<int> CategoryID
		{
			get
			{
				return this._CategoryID;
			}
			set
			{
				if ((this._CategoryID != value))
				{
					this._CategoryID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RegionalManagerList")]
	public partial class RegionalManagerList
	{
		
		private int _Id;
		
		private string _RegionalManagerName;
		
		private System.Nullable<int> _RegionID;
		
		public RegionalManagerList()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegionalManagerName", DbType="VarChar(MAX)")]
		public string RegionalManagerName
		{
			get
			{
				return this._RegionalManagerName;
			}
			set
			{
				if ((this._RegionalManagerName != value))
				{
					this._RegionalManagerName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegionID", DbType="Int")]
		public System.Nullable<int> RegionID
		{
			get
			{
				return this._RegionID;
			}
			set
			{
				if ((this._RegionID != value))
				{
					this._RegionID = value;
				}
			}
		}
	}
	
	public partial class DeleteCustomerResult
	{
		
		private System.Nullable<bool> _Column1;
		
		public DeleteCustomerResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Bit")]
		public System.Nullable<bool> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class DeleteProductResult
	{
		
		private System.Nullable<bool> _Column1;
		
		public DeleteProductResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Bit")]
		public System.Nullable<bool> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class GetGridcolumnsByUserResult
	{
		
		private string _username;
		
		private string _gridcolumns;
		
		public GetGridcolumnsByUserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this._username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gridcolumns", DbType="VarChar(1500)")]
		public string gridcolumns
		{
			get
			{
				return this._gridcolumns;
			}
			set
			{
				if ((this._gridcolumns != value))
				{
					this._gridcolumns = value;
				}
			}
		}
	}
	
	public partial class GetViewsByUserResult
	{
		
		private string _username;
		
		private string _gridname;
		
		private string _gridcolumns;
		
		public GetViewsByUserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this._username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gridname", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string gridname
		{
			get
			{
				return this._gridname;
			}
			set
			{
				if ((this._gridname != value))
				{
					this._gridname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gridcolumns", DbType="VarChar(1500)")]
		public string gridcolumns
		{
			get
			{
				return this._gridcolumns;
			}
			set
			{
				if ((this._gridcolumns != value))
				{
					this._gridcolumns = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
